### ISSUE TITLE
BfA: Combo Points not working

### ISSUE THREAD

**Issue by nyyr** [nyyr/ArcHUD3#24]

**Comment by Chickenchasr** [comment]
Hi, i think the culprit here might be UNIT_POWER_FREQUENT. It might have been retired in bfa. UNIT_POWER itself has changed to UNIT_POWER_UPDATE. i think if you replace the UNIT_POWER_FREQUENT with UNIT_POWER_UPDATE this should work. Give it a try and let me know. I will try to free up some disk space to try it out myself.
